// Generated by FINAL/scripts/gen_panel_i18n.py — keep in sync with PhantomLocalize.m
window.PANEL_I18N_CATALOG = {
  "tab_home": {
    "en": "Home",
    "es": "Inicio",
    "pt": "Início",
    "vi": "Trang chủ",
    "ar": "الرئيسية",
    "ru": "Главная"
  },
  "tab_skin": {
    "en": "Skin",
    "es": "Skin",
    "pt": "Skin",
    "vi": "Skin",
    "ar": "Skin",
    "ru": "Skin"
  },
  "tab_clean": {
    "en": "Clean",
    "es": "Limpiar",
    "pt": "Limpar",
    "vi": "Dọn",
    "ar": "تنظيف",
    "ru": "Очистка"
  },
  "tab_misc": {
    "en": "Misc",
    "es": "Misc",
    "pt": "Misc",
    "vi": "Misc",
    "ar": "Misc",
    "ru": "Misc"
  },
  "tab_account": {
    "en": "Account",
    "es": "Cuenta",
    "pt": "Conta",
    "vi": "Tài khoản",
    "ar": "الحساب",
    "ru": "Аккаунт"
  },
  "sign_in": {
    "en": "Sign In",
    "es": "Iniciar sesión",
    "pt": "Entrar",
    "vi": "Đăng nhập",
    "ar": "تسجيل الدخول",
    "ru": "Войти"
  },
  "license_key": {
    "en": "License key",
    "es": "Clave de licencia",
    "pt": "Chave de licença",
    "vi": "Khóa bản quyền",
    "ar": "مفتاح الترخيص",
    "ru": "Лицензионный ключ"
  },
  "paste_key": {
    "en": "Paste key",
    "es": "Pegar clave",
    "pt": "Colar chave",
    "vi": "Dán khóa",
    "ar": "لصق المفتاح",
    "ru": "Вставить ключ"
  },
  "remember": {
    "en": "Remember",
    "es": "Recordar",
    "pt": "Lembrar",
    "vi": "Ghi nhớ",
    "ar": "تذكر",
    "ru": "Запомнить"
  },
  "injecting": {
    "en": "Injecting…",
    "es": "Inyectando…",
    "pt": "Injetando…",
    "vi": "Đang inject…",
    "ar": "جاري الحقن…",
    "ru": "Inject…"
  },
  "launch": {
    "en": "Launch",
    "es": "Iniciar",
    "pt": "Iniciar",
    "vi": "Khởi chạy",
    "ar": "تشغيل",
    "ru": "Запуск"
  },
  "launching": {
    "en": "Launching",
    "es": "Iniciando",
    "pt": "Iniciando",
    "vi": "Đang khởi chạy",
    "ar": "جاري التشغيل",
    "ru": "Запуск…"
  },
  "initializing": {
    "en": "INITIALIZING PANEL…",
    "es": "INICIANDO PANEL…",
    "pt": "INICIANDO PAINEL…",
    "vi": "ĐANG KHỞI TẠO…",
    "ar": "جاري تهيئة اللوحة…",
    "ru": "ИНИЦИАЛИЗАЦИЯ…"
  },
  "ready": {
    "en": "READY",
    "es": "LISTO",
    "pt": "PRONTO",
    "vi": "SẴN SÀNG",
    "ar": "جاهز",
    "ru": "ГОТОВО"
  },
  "choose_aim": {
    "en": "Choose aim",
    "es": "Elegir aim",
    "pt": "Escolher aim",
    "vi": "Chọn aim",
    "ar": "اختر التصويب",
    "ru": "Выберите aim"
  },
  "no_esp_selected": {
    "en": "No ESP selected",
    "es": "Sin ESP seleccionado",
    "pt": "Nenhum ESP selecionado",
    "vi": "Chưa chọn ESP",
    "ar": "لم يتم اختيار ESP",
    "ru": "ESP не выбран"
  },
  "aimbots": {
    "en": "Aimbots",
    "es": "Aimbots",
    "pt": "Aimbots",
    "vi": "Aimbots",
    "ar": "Aimbots",
    "ru": "Aimbots"
  },
  "esp": {
    "en": "ESP",
    "es": "ESP",
    "pt": "ESP",
    "vi": "ESP",
    "ar": "ESP",
    "ru": "ESP"
  },
  "inject": {
    "en": "Inject",
    "es": "Inyectar",
    "pt": "Injetar",
    "vi": "Inject",
    "ar": "حقن",
    "ru": "Inject"
  },
  "restore_original": {
    "en": "Restore Original",
    "es": "Restaurar original",
    "pt": "Restaurar original",
    "vi": "Khôi phục",
    "ar": "استعادة الأصل",
    "ru": "Восстановить"
  },
  "free_fire": {
    "en": "Free Fire",
    "es": "Free Fire",
    "pt": "Free Fire",
    "vi": "Free Fire",
    "ar": "Free Fire",
    "ru": "Free Fire"
  },
  "ff_max": {
    "en": "FF Max",
    "es": "FF Max",
    "pt": "FF Max",
    "vi": "FF Max",
    "ar": "FF Max",
    "ru": "FF Max"
  },
  "aim_v1": {
    "en": "Aim V1",
    "es": "Aim V1",
    "pt": "Aim V1",
    "vi": "Aim V1",
    "ar": "Aim V1",
    "ru": "Aim V1"
  },
  "aim_v2": {
    "en": "Aim V2",
    "es": "Aim V2",
    "pt": "Aim V2",
    "vi": "Aim V2",
    "ar": "Aim V2",
    "ru": "Aim V2"
  },
  "character": {
    "en": "Character",
    "es": "Personaje",
    "pt": "Personagem",
    "vi": "Nhân vật",
    "ar": "الشخصية",
    "ru": "Персонаж"
  },
  "select_skins": {
    "en": "Select skins",
    "es": "Elegir skins",
    "pt": "Selecionar skins",
    "vi": "Chọn skin",
    "ar": "اختر السkins",
    "ru": "Выбрать skins"
  },
  "skin_ff": {
    "en": "Skin - Free Fire",
    "es": "Skin - Free Fire",
    "pt": "Skin - Free Fire",
    "vi": "Skin - Free Fire",
    "ar": "Skin - Free Fire",
    "ru": "Skin - Free Fire"
  },
  "dimitri_skins": {
    "en": "Dimitri skins",
    "es": "Skins de Dimitri",
    "pt": "Skins Dimitri",
    "vi": "Skin Dimitri",
    "ar": "skins ديميتري",
    "ru": "Skins Dimitri"
  },
  "alok_skins": {
    "en": "Alok skins",
    "es": "Skins de Alok",
    "pt": "Skins Alok",
    "vi": "Skin Alok",
    "ar": "skins ألوك",
    "ru": "Skins Alok"
  },
  "clean_aim_v1": {
    "en": "Clean Aim V1",
    "es": "Limpiar Aim V1",
    "pt": "Limpar Aim V1",
    "vi": "Dọn Aim V1",
    "ar": "تنظيف Aim V1",
    "ru": "Очистить Aim V1"
  },
  "clean_aim_v2": {
    "en": "Clean Aim V2",
    "es": "Limpiar Aim V2",
    "pt": "Limpar Aim V2",
    "vi": "Dọn Aim V2",
    "ar": "تنظيف Aim V2",
    "ru": "Очистить Aim V2"
  },
  "clean_esp": {
    "en": "Clean ESP",
    "es": "Limpiar ESP",
    "pt": "Limpar ESP",
    "vi": "Dọn ESP",
    "ar": "تنظيف ESP",
    "ru": "Очистить ESP"
  },
  "reset_all": {
    "en": "Reset all",
    "es": "Restablecer todo",
    "pt": "Redefinir tudo",
    "vi": "Đặt lại tất cả",
    "ar": "إعادة ضبط الكل",
    "ru": "Сбросить всё"
  },
  "aim_esp": {
    "en": "Aim + ESP",
    "es": "Aim + ESP",
    "pt": "Aim + ESP",
    "vi": "Aim + ESP",
    "ar": "Aim + ESP",
    "ru": "Aim + ESP"
  },
  "inject_method": {
    "en": "Inject method",
    "es": "Método de inyección",
    "pt": "Método de injeção",
    "vi": "Phương thức inject",
    "ar": "طريقة الحقن",
    "ru": "Метод inject"
  },
  "check_path": {
    "en": "Check path",
    "es": "Comprobar ruta",
    "pt": "Verificar caminho",
    "vi": "Kiểm tra đường dẫn",
    "ar": "فحص المسار",
    "ru": "Проверить путь"
  },
  "auto": {
    "en": "Auto",
    "es": "Auto",
    "pt": "Auto",
    "vi": "Auto",
    "ar": "Auto",
    "ru": "Auto"
  },
  "auto_v2": {
    "en": "Auto V2",
    "es": "Auto V2",
    "pt": "Auto V2",
    "vi": "Auto V2",
    "ar": "Auto V2",
    "ru": "Auto V2"
  },
  "auto_selected": {
    "en": "Auto selected",
    "es": "Auto seleccionado",
    "pt": "Auto selecionado",
    "vi": "Đã chọn Auto",
    "ar": "تم اختيار Auto",
    "ru": "Выбран Auto"
  },
  "auto_v2_selected": {
    "en": "Auto V2 selected",
    "es": "Auto V2 seleccionado",
    "pt": "Auto V2 selecionado",
    "vi": "Đã chọn Auto V2",
    "ar": "تم اختيار Auto V2",
    "ru": "Выбран Auto V2"
  },
  "applied_ok": {
    "en": "Applied successfully",
    "es": "Aplicado",
    "pt": "Aplicado",
    "vi": "Áp dụng thành công",
    "ar": "تم التطبيق",
    "ru": "Применено"
  },
  "resetting": {
    "en": "Resetting…",
    "es": "Restableciendo…",
    "pt": "Redefinindo…",
    "vi": "Đang đặt lại…",
    "ar": "جاري إعادة الضبط…",
    "ru": "Сброс…"
  },
  "reset_ok": {
    "en": "Reset successful",
    "es": "Restablecido",
    "pt": "Redefinido",
    "vi": "Đặt lại thành công",
    "ar": "تمت إعادة الضبط",
    "ru": "Сброс выполнен"
  },
  "applying": {
    "en": "Applying",
    "es": "Aplicando",
    "pt": "Aplicando",
    "vi": "Đang áp dụng",
    "ar": "جاري التطبيق",
    "ru": "Применение…"
  },
  "applied": {
    "en": "Applied",
    "es": "Aplicado",
    "pt": "Aplicado",
    "vi": "Đã áp dụng",
    "ar": "تم التطبيق",
    "ru": "Применено"
  },
  "failed": {
    "en": "Failed",
    "es": "Falló",
    "pt": "Falhou",
    "vi": "Thất bại",
    "ar": "فشل",
    "ru": "Ошибка"
  },
  "cleaning": {
    "en": "Cleaning",
    "es": "Limpiando",
    "pt": "Limpando",
    "vi": "Đang dọn",
    "ar": "جاري التنظيف",
    "ru": "Очистка…"
  },
  "cleaned": {
    "en": "Cleaned",
    "es": "Limpiado",
    "pt": "Limpo",
    "vi": "Đã dọn",
    "ar": "تم التنظيف",
    "ru": "Очищено"
  },
  "nothing_to_clean": {
    "en": "Nothing to clean",
    "es": "Nada que limpiar",
    "pt": "Nada para limpar",
    "vi": "Không có gì để dọn",
    "ar": "لا يوجد شيء للتنظيف",
    "ru": "Нечего очищать"
  },
  "time_left": {
    "en": "Time left",
    "es": "Tiempo restante",
    "pt": "Tempo restante",
    "vi": "Thời gian còn lại",
    "ar": "الوقت المتبقي",
    "ru": "Осталось"
  },
  "copy": {
    "en": "Copy",
    "es": "Copiar",
    "pt": "Copiar",
    "vi": "Sao chép",
    "ar": "نسخ",
    "ru": "Копировать"
  },
  "copied": {
    "en": "Copied",
    "es": "Copiado",
    "pt": "Copiado",
    "vi": "Đã sao chép",
    "ar": "تم النسخ",
    "ru": "Скопировано"
  },
  "license": {
    "en": "License",
    "es": "Licencia",
    "pt": "Licença",
    "vi": "Bản quyền",
    "ar": "الترخيص",
    "ru": "Лицензия"
  },
  "issued": {
    "en": "Issued",
    "es": "Emitido",
    "pt": "Emitido",
    "vi": "Cấp ngày",
    "ar": "تاريخ الإصدار",
    "ru": "Выдано"
  },
  "expiry_date": {
    "en": "Expiry date",
    "es": "Fecha de vencimiento",
    "pt": "Data de expiração",
    "vi": "Ngày hết hạn",
    "ar": "تاريخ الانتهاء",
    "ru": "Истекает"
  },
  "session": {
    "en": "Session",
    "es": "Sesión",
    "pt": "Sessão",
    "vi": "Phiên",
    "ar": "الجلسة",
    "ru": "Сессия"
  },
  "signed_in": {
    "en": "Signed in",
    "es": "Conectado",
    "pt": "Conectado",
    "vi": "Đã đăng nhập",
    "ar": "مسجل الدخول",
    "ru": "Вход"
  },
  "validity": {
    "en": "Validity",
    "es": "Validez",
    "pt": "Validade",
    "vi": "Hiệu lực",
    "ar": "الصلاحية",
    "ru": "Срок"
  },
  "credits": {
    "en": "Credits",
    "es": "Créditos",
    "pt": "Créditos",
    "vi": "Credits",
    "ar": "Credits",
    "ru": "Credits"
  },
  "sign_out": {
    "en": "Sign Out",
    "es": "Cerrar sesión",
    "pt": "Sair",
    "vi": "Đăng xuất",
    "ar": "تسجيل الخروج",
    "ru": "Выйти"
  },
  "language": {
    "en": "Language",
    "es": "Idioma",
    "pt": "Idioma",
    "vi": "Ngôn ngữ",
    "ar": "اللغة",
    "ru": "Язык"
  },
  "choose_language": {
    "en": "Choose language",
    "es": "Elegir idioma",
    "pt": "Escolher idioma",
    "vi": "Chọn ngôn ngữ",
    "ar": "اختر اللغة",
    "ru": "Выберите язык"
  },
  "cancel": {
    "en": "Cancel",
    "es": "Cancelar",
    "pt": "Cancelar",
    "vi": "Hủy",
    "ar": "إلغاء",
    "ru": "Отмена"
  },
  "active_license": {
    "en": "Active license",
    "es": "Licencia activa",
    "pt": "Licença ativa",
    "vi": "Bản quyền hoạt động",
    "ar": "ترخيص نشط",
    "ru": "Активная лицензия"
  },
  "menu_off": {
    "en": "This menu is turned off",
    "es": "Este menú está desactivado",
    "pt": "Este menu está desativado",
    "vi": "Menu này đã tắt",
    "ar": "هذه القائمة معطلة",
    "ru": "Меню отключено"
  },
  "misc_off": {
    "en": "Misc is turned off",
    "es": "Misc está desactivado",
    "pt": "Misc está desativado",
    "vi": "Misc đã tắt",
    "ar": "Misc معطل",
    "ru": "Misc отключён"
  },
  "skin_off": {
    "en": "Skin is turned off",
    "es": "Skin está desactivado",
    "pt": "Skin está desativado",
    "vi": "Skin đã tắt",
    "ar": "Skin معطل",
    "ru": "Skin отключён"
  },
  "function_off": {
    "en": "Function turned off",
    "es": "Función desactivada",
    "pt": "Função desativada",
    "vi": "Chức năng đã tắt",
    "ar": "الوظيفة معطلة",
    "ru": "Функция отключена"
  },
  "enter_license": {
    "en": "Enter a license key",
    "es": "Introduce una clave",
    "pt": "Digite uma chave",
    "vi": "Nhập khóa bản quyền",
    "ar": "أدخل مفتاح الترخيص",
    "ru": "Введите ключ"
  },
  "owner_role": {
    "en": "Owner",
    "es": "Propietario",
    "pt": "Dono",
    "vi": "Chủ sở hữu",
    "ar": "المالك",
    "ru": "Владелец"
  },
  "server_role": {
    "en": "Official server",
    "es": "Servidor oficial",
    "pt": "Servidor oficial",
    "vi": "Máy chủ chính thức",
    "ar": "الخادم الرسمي",
    "ru": "Официальный сервер"
  },
  "under_update": {
    "en": "This is under update",
    "es": "En actualización",
    "pt": "Em atualização",
    "vi": "Đang cập nhật",
    "ar": "قيد التحديث",
    "ru": "Обновление"
  },
  "close": {
    "en": "Close",
    "es": "Cerrar",
    "pt": "Fechar",
    "vi": "Đóng",
    "ar": "إغلاق",
    "ru": "Закрыть"
  },
  "key_label": {
    "en": "Key",
    "es": "Clave",
    "pt": "Chave",
    "vi": "Khóa",
    "ar": "المفتاح",
    "ru": "Ключ"
  },
  "patch_drag": {
    "en": "Drag",
    "es": "Drag",
    "pt": "Drag",
    "vi": "Drag",
    "ar": "Drag",
    "ru": "Drag"
  },
  "patch_neck": {
    "en": "Neck",
    "es": "Neck",
    "pt": "Neck",
    "vi": "Neck",
    "ar": "Neck",
    "ru": "Neck"
  },
  "patch_body": {
    "en": "Body",
    "es": "Body",
    "pt": "Body",
    "vi": "Body",
    "ar": "Body",
    "ru": "Body"
  },
  "patch_magic": {
    "en": "Magic",
    "es": "Magic",
    "pt": "Magic",
    "vi": "Magic",
    "ar": "Magic",
    "ru": "Magic"
  },
  "patch_aimlock": {
    "en": "Aimlock",
    "es": "Aimlock",
    "pt": "Aimlock",
    "vi": "Aimlock",
    "ar": "Aimlock",
    "ru": "Aimlock"
  },
  "patch_head": {
    "en": "Head",
    "es": "Head",
    "pt": "Head",
    "vi": "Head",
    "ar": "Head",
    "ru": "Head"
  },
  "patch_green": {
    "en": "Green",
    "es": "Verde",
    "pt": "Verde",
    "vi": "Xanh lá",
    "ar": "أخضر",
    "ru": "Зелёный"
  },
  "patch_cyan": {
    "en": "Cyan",
    "es": "Cian",
    "pt": "Ciano",
    "vi": "Xanh lơ",
    "ar": "سماوي",
    "ru": "Голубой"
  },
  "patch_pink": {
    "en": "Pink",
    "es": "Rosa",
    "pt": "Rosa",
    "vi": "Hồng",
    "ar": "وردي",
    "ru": "Розовый"
  },
  "patch_full_body": {
    "en": "Full Body",
    "es": "Cuerpo completo",
    "pt": "Corpo inteiro",
    "vi": "Toàn thân",
    "ar": "الجسم كامل",
    "ru": "Всё тело"
  },
  "patch_magic_bullet": {
    "en": "Magic Bullet",
    "es": "Magic Bullet",
    "pt": "Magic Bullet",
    "vi": "Magic Bullet",
    "ar": "Magic Bullet",
    "ru": "Magic Bullet"
  },
  "patch_head_antenna": {
    "en": "Head Antenna",
    "es": "Head Antenna",
    "pt": "Head Antenna",
    "vi": "Head Antenna",
    "ar": "Head Antenna",
    "ru": "Head Antenna"
  },
  "patch_drag_antenna": {
    "en": "Drag Antenna",
    "es": "Drag Antenna",
    "pt": "Drag Antenna",
    "vi": "Drag Antenna",
    "ar": "Drag Antenna",
    "ru": "Drag Antenna"
  },
  "patch_body_antenna": {
    "en": "Body Antenna",
    "es": "Body Antenna",
    "pt": "Body Antenna",
    "vi": "Body Antenna",
    "ar": "Body Antenna",
    "ru": "Body Antenna"
  },
  "patch_weapon_green": {
    "en": "Weapon Green",
    "es": "Arma verde",
    "pt": "Arma verde",
    "vi": "Vũ khí xanh",
    "ar": "سلاح أخضر",
    "ru": "Оружие зел."
  },
  "patch_weapon_cyan": {
    "en": "Weapon Cyan",
    "es": "Arma cian",
    "pt": "Arma ciano",
    "vi": "Vũ khí xanh lơ",
    "ar": "سلاح سماوي",
    "ru": "Оружие гол."
  },
  "patch_weapon_pink": {
    "en": "Weapon Pink",
    "es": "Arma rosa",
    "pt": "Arma rosa",
    "vi": "Vũ khí hồng",
    "ar": "سلاح وردي",
    "ru": "Оружие роз."
  },
  "patch_full_body_esp": {
    "en": "Full Body ESP",
    "es": "ESP cuerpo",
    "pt": "ESP corpo",
    "vi": "ESP toàn thân",
    "ar": "ESP الجسم",
    "ru": "ESP тело"
  },
  "modules": {
    "en": "Modules",
    "es": "Módulos",
    "pt": "Módulos",
    "vi": "Modules",
    "ar": "الوحدات",
    "ru": "Модули"
  },
  "esp_colors": {
    "en": "ESP Colors",
    "es": "Colores ESP",
    "pt": "Cores ESP",
    "vi": "Màu ESP",
    "ar": "ألوان ESP",
    "ru": "Цвета ESP"
  },
  "game": {
    "en": "Game",
    "es": "Juego",
    "pt": "Jogo",
    "vi": "Game",
    "ar": "اللعبة",
    "ru": "Игра"
  },
  "aim": {
    "en": "Aim",
    "es": "Aim",
    "pt": "Aim",
    "vi": "Aim",
    "ar": "Aim",
    "ru": "Aim"
  },
  "aimbot": {
    "en": "Aimbot",
    "es": "Aimbot",
    "pt": "Aimbot",
    "vi": "Aimbot",
    "ar": "Aimbot",
    "ru": "Aimbot"
  },
  "visual": {
    "en": "Visual",
    "es": "Visual",
    "pt": "Visual",
    "vi": "Visual",
    "ar": "Visual",
    "ru": "Visual"
  },
  "not_set": {
    "en": "Not set",
    "es": "Sin elegir",
    "pt": "Não definido",
    "vi": "Chưa chọn",
    "ar": "غير محدد",
    "ru": "Не выбрано"
  },
  "roster": {
    "en": "Roster",
    "es": "Plantilla",
    "pt": "Elenco",
    "vi": "Danh sách",
    "ar": "القائمة",
    "ru": "Состав"
  },
  "skins_available": {
    "en": "8 skins available",
    "es": "8 skins disponibles",
    "pt": "8 skins disponíveis",
    "vi": "Có 8 skin",
    "ar": "8 skins متاحة",
    "ru": "8 skins"
  },
  "misc_patches": {
    "en": "Misc patches",
    "es": "Parches misc",
    "pt": "Patches misc",
    "vi": "Patch misc",
    "ar": "رقع Misc",
    "ru": "Misc патчи"
  },
  "community": {
    "en": "Community",
    "es": "Comunidad",
    "pt": "Comunidade",
    "vi": "Cộng đồng",
    "ar": "المجتمع",
    "ru": "Сообщество"
  },
  "strip_aim": {
    "en": "Strip aim patches",
    "es": "Quitar aim",
    "pt": "Remover aim",
    "vi": "Gỡ aim",
    "ar": "إزالة aim",
    "ru": "Снять aim"
  },
  "remove_visuals": {
    "en": "Remove visuals",
    "es": "Quitar visuales",
    "pt": "Remover visuais",
    "vi": "Gỡ visual",
    "ar": "إزالة المرئيات",
    "ru": "Убрать визуал"
  },
  "clean_misc": {
    "en": "Clean Misc",
    "es": "Limpiar Misc",
    "pt": "Limpar Misc",
    "vi": "Dọn Misc",
    "ar": "تنظيف Misc",
    "ru": "Очистить Misc"
  },
  "reset_guest": {
    "en": "Reset Guest",
    "es": "Reset Guest",
    "pt": "Reset Guest",
    "vi": "Reset Guest",
    "ar": "Reset Guest",
    "ru": "Reset Guest"
  },
  "reset_guest_clean": {
    "en": "Reset Guest - Clean",
    "es": "Reset Guest - Clean",
    "pt": "Reset Guest - Clean",
    "vi": "Reset Guest - Clean",
    "ar": "Reset Guest - Clean",
    "ru": "Reset Guest - Clean"
  },
  "misc_n": {
    "en": "Misc",
    "es": "Misc",
    "pt": "Misc",
    "vi": "Misc",
    "ar": "Misc",
    "ru": "Misc"
  },
  "injected_ok": {
    "en": "Injected successfully",
    "es": "Inyectado",
    "pt": "Injetado",
    "vi": "Inject thành công",
    "ar": "تم الحقن",
    "ru": "Inject OK"
  },
  "inject_failed": {
    "en": "Injection failed",
    "es": "Falló la inyección",
    "pt": "Falha na injeção",
    "vi": "Inject thất bại",
    "ar": "فشل الحقن",
    "ru": "Ошибка inject"
  },
  "restored_ok": {
    "en": "Back Restored",
    "es": "Restaurado",
    "pt": "Restaurado",
    "vi": "Đã khôi phục",
    "ar": "تمت الاستعادة",
    "ru": "Восстановлено"
  },
  "restore_failed": {
    "en": "Restore failed",
    "es": "Falló restaurar",
    "pt": "Falha ao restaurar",
    "vi": "Khôi phục thất bại",
    "ar": "فشلت الاستعادة",
    "ru": "Ошибка восстановления"
  },
  "cleaned_ok": {
    "en": "Cleaned successfully",
    "es": "Limpiado",
    "pt": "Limpo",
    "vi": "Dọn thành công",
    "ar": "تم التنظيف",
    "ru": "Очищено"
  },
  "clean_failed": {
    "en": "Clean failed",
    "es": "Falló limpiar",
    "pt": "Falha ao limpar",
    "vi": "Dọn thất bại",
    "ar": "فشل التنظيف",
    "ru": "Ошибка очистки"
  },
  "signed_out": {
    "en": "Signed out",
    "es": "Sesión cerrada",
    "pt": "Saiu",
    "vi": "Đã đăng xuất",
    "ar": "تم تسجيل الخروج",
    "ru": "Выход"
  },
  "skins": {
    "en": "Skins",
    "es": "Skins",
    "pt": "Skins",
    "vi": "Skins",
    "ar": "Skins",
    "ru": "Skins"
  },
  "developer_role": {
    "en": "Developer",
    "es": "Desarrollador",
    "pt": "Desenvolvedor",
    "vi": "Developer",
    "ar": "المطور",
    "ru": "Разработчик"
  },
  "expired": {
    "en": "Expired",
    "es": "Expirado",
    "pt": "Expirado",
    "vi": "Hết hạn",
    "ar": "منتهي",
    "ru": "Истекло"
  },
  "ff_short": {
    "en": "FF",
    "es": "FF",
    "pt": "FF",
    "vi": "FF",
    "ar": "FF",
    "ru": "FF"
  },
  "ffm_short": {
    "en": "FFM",
    "es": "FFM",
    "pt": "FFM",
    "vi": "FFM",
    "ar": "FFM",
    "ru": "FFM"
  },
  "show_key": {
    "en": "Show key",
    "es": "Mostrar clave",
    "pt": "Mostrar chave",
    "vi": "Hiện khóa",
    "ar": "إظهار المفتاح",
    "ru": "Показать ключ"
  },
  "hide_key": {
    "en": "Hide key",
    "es": "Ocultar clave",
    "pt": "Ocultar chave",
    "vi": "Ẩn khóa",
    "ar": "إخفاء المفتاح",
    "ru": "Скрыть ключ"
  },
  "external_tag": {
    "en": "iOS · External",
    "es": "iOS · External",
    "pt": "iOS · External",
    "vi": "iOS · External",
    "ar": "iOS · External",
    "ru": "iOS · External"
  },
  "checking_license": {
    "en": "Checking license…",
    "es": "Comprobando…",
    "pt": "Verificando…",
    "vi": "Đang kiểm tra…",
    "ar": "جاري التحقق…",
    "ru": "Проверка…"
  },
  "menu_off_toast": {
    "en": "This menu is turned off",
    "es": "Este menú está desactivado",
    "pt": "Este menu está desativado",
    "vi": "Menu này đã tắt",
    "ar": "هذه القائمة معطلة",
    "ru": "Меню отключено"
  },
  "skins_off_toast": {
    "en": "Skins are turned off",
    "es": "Skins desactivados",
    "pt": "Skins desativados",
    "vi": "Skin đã tắt",
    "ar": "Skins معطلة",
    "ru": "Skins отключены"
  },
  "days": {
    "en": "days",
    "es": "días",
    "pt": "dias",
    "vi": "ngày",
    "ar": "أيام",
    "ru": "дн."
  },
  "day": {
    "en": "day",
    "es": "día",
    "pt": "dia",
    "vi": "ngày",
    "ar": "يوم",
    "ru": "день"
  }
};
window.PANEL_LANG_OPTIONS = [
  {
    "code": "en",
    "name": "English"
  },
  {
    "code": "es",
    "name": "Español"
  },
  {
    "code": "pt",
    "name": "Português"
  },
  {
    "code": "vi",
    "name": "Tiếng Việt"
  },
  {
    "code": "ar",
    "name": "العربية"
  },
  {
    "code": "ru",
    "name": "Русский"
  }
];

(function (g) {
  var STORE = 'ox.panel.language';
  function code() {
    try {
      var c = localStorage.getItem(STORE) || 'en';
      for (var i = 0; i < g.PANEL_LANG_OPTIONS.length; i++) {
        if (g.PANEL_LANG_OPTIONS[i].code === c) return c;
      }
    } catch (e) {}
    return 'en';
  }
  function setCode(c) {
    try { localStorage.setItem(STORE, c || 'en'); } catch (e) {}
    g.document.documentElement.dir = (c === 'ar') ? 'rtl' : 'ltr';
    apply();
  }
  function t(key) {
    var cat = g.PANEL_I18N_CATALOG[key];
    if (!cat) return key;
    var lang = code();
    return cat[lang] || cat.en || key;
  }
  function apply() {
    g.document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var k = el.getAttribute('data-i18n');
      if (!k) return;
      var val = t(k);
      var attr = el.getAttribute('data-i18n-attr');
      if (attr) {
        el.setAttribute(attr, val);
        return;
      }
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = val;
        return;
      }
      el.textContent = val;
    });
    g.document.querySelectorAll('.patch-btn').forEach(function (btn) {
      var span = btn.querySelector('[data-i18n]');
      if (span && span.textContent) btn.setAttribute('data-label', span.textContent);
    });
    var lv = g.document.getElementById('language-value');
    if (lv) {
      var name = 'English';
      var c = code();
      g.PANEL_LANG_OPTIONS.forEach(function (o) { if (o.code === c) name = o.name; });
      lv.textContent = name;
    }
    if (typeof g.onPanelI18nApplied === 'function') {
      try { g.onPanelI18nApplied(); } catch (e) {}
    }
  }
  g.panelI18n = { t: t, apply: apply, code: code, setCode: setCode, options: g.PANEL_LANG_OPTIONS };
  if (g.document.readyState === 'loading') {
    g.document.addEventListener('DOMContentLoaded', apply);
  } else {
    apply();
  }
})(window);
